### PR TITLE
Replace Skystone field image with Ultimate Goal field image

### PR DESCRIPTION
**Pull request by NoahBres**
Replace Skystone (2019-20) field image with Ultimate Goal (2020-21) field image

### CODE REVIEW

**Comment by rbrott** [comment]
That was fast... #28 

Are the red and purple rectangles intentionally misaligned? I'm fine merging whatever the community decides upon, but I don't want to do it twice.

**Comment by NoahBres** [comment]
Oh I didn't even notice that issue :P 

That image is directly from gm2. I just screenshotted and cleaned it up. Screen Shot 2020-09-15 at 12 01 21 PM

**Comment by NoahBres** [comment]
Ah by asymmetry you mean the purple/red rectangles. Just measured and they do have like a 5px discrepancy. Hm.

**Comment by NoahBres** [comment]
Currently trying to reach out to vendors on the Discord to ask about the field weirdness (there are _slightly_ conflicting field images in gm2) so going to see if I can get an absolutely correct one. Will update this PR once I get something solid. My apologies for the oversight.

**Comment by NoahBres** [comment]
Added a _much_ improved field image (based on a CAD rendering of the official Andymark field CAD, courtesy of @dansman805).
Slightly cleaned up. Removed walls. Removed some artifacts. Should be great. Symmetrical crop. Everything should be lined up.

field

**Comment by rbrott** [comment]
Nit: should the blue wobble goal have a red base?

**Pull request merged**
